before_script:
  - docker info

build_image:
  stage: build
  script:
    - docker build -t acme-dns .

deploy_production:
  stage: deploy
  script:
    - echo "Deploy to production server"
  environment:
    name: production
    url: https://dns.herzo.gs
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual