before_script:
  - docker info

build_image:
  stage: build
  script:
    - env
    - envsubst < data/acme-dns/config/template.cfg > data/acme-dns/config/config.cfg
    - docker build -t acme-dns .
  environment:
    name: production
    url: https://dns.herzo.gs

deploy_production:
  stage: deploy
  script:
    - envsubst < data/acme-dns/config/template.cfg  > data/acme-dns/config/config.cfg
    - chown -R 1994:1994 data/acme-dns/
    - docker-compose up -d --build --remove-orphans
  environment:
    name: production
    url: https://dns.herzo.gs
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual
