before_script:
  - docker info

build_image:
  stage: build
  script:
    - docker build -t acme-dns .

deploy_production:
  stage: deploy
  script:
    - cp .env.example .acme.env
    - source .acme.env
    - envsubst < config/template.cfg  > config/config.cfg
    - docker-compose up -d --build --remove-orphans
  environment:
    name: production
    url: https://dns.herzo.gs
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual