---
version: '2'
services:
  acme-dns:
    image: git.knopp.it:5050/p.herzog/docker-acme-dns:latest
    container_name: acme-dns
    restart: unless-stopped
    ports:
      - "${EXTERNAL_IP_API}:80:80"
      - "${EXTERNAL_IP_API}:443:443"
      - "${EXTERNAL_IP_DNS}:53:53"
      - "${EXTERNAL_IP_DNS}:53:53/udp"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DNS_ZONE: ${DNS_ZONE}
      DNS_ZONE_SERVER: ${DNS_ZONE_SERVER}
      NS_ADMIN_MAIL: ${NS_ADMIN_MAIL}
      DB_ENGINE: ${DB_ENGINE}
      ACME_SERVICE: ${ACME_SERVICE}
      NOTIFICATION_MAIL: ${NOTIFICATION_MAIL}
      EXTERNAL_IP_DNS: ${EXTERNAL_IP_DNS}
    volumes:
      - api-certs:/var/lib/acme-dns/api-certs:rw
    depends_on:
      - database
  database:
    container_name: database
    hostname: database
    image: postgres:alpine
    restart: always
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

volumes:
  api-certs:
  postgresql_data:
