version: '2'
services:
  acme-dns:
    build:
      context: .
    container_name: acme-dns
    ports:
      - "${EXTERNAL_IP_API}:443:443"
      - "${EXTERNAL_IP_DNS}:53:53"
      - "${EXTERNAL_IP_DNS}:53:53/udp"
      - "${EXTERNAL_IP_API}:80:80"
    volumes:
      - ./data/acme-dns/api-certs/:/var/lib/acme-dns/api-certs
    depends_on:
      - database
  database:
    container_name: database
    hostname: database
    image: postgres:alpine
    restart: always
    user: gitlab-runner
    volumes:
      - ./data/postgresql/data:/var/lib/postgresql/data
      - /etc/passwd:/etc/passwd:ro
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
